### ISSUE TITLE
登录不上，需要VPN？

### ISSUE THREAD

**Issue by yy1234** [line/line-sdk-ios-swift#11]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. LINE SDK version, Xcode version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
Hi,

As I know, LINE service is blocked in China, so you cannot use it if you are located in the Chinese mainland. We are now cannot provide support or service access for Chinese users.

Please check our [Terms and Conditions of Use](https://terms.line.me/line_terms/) and [Privacy Policy](https://terms.line.me/line_rules/) to know more about the service providing status worldwide.

Since this is actually not an issue related to SDK itself in technique category, I am closing it.

If you have any concerns, feel free to contact our legal or security support team instead:

LINE Legal Support <dl_line_legal@linecorp.com>
LINE Security Support <dl_legal_security@linecorp.com>
