### ISSUE TITLE
Xcode 14 beta 1 Carthage build fail

### ISSUE THREAD

**Issue by kkdayitbobson** [line/line-sdk-ios-swift#153]
Xcode 14 beta 1 Carthage build fail

<img width="545" alt="截圖 2020-07-09 下午5 38 01" src="https://user-images.githubusercontent.com/28857830/87023959-13276880-c20b-11ea-8033-ee5d05903e73.png">

<img width="2113" alt="截圖 2020-07-09 下午5 38 13" src="https://user-images.githubusercontent.com/28857830/87023968-16baef80-c20b-11ea-8cd3-bd927bc5aed7.png">

**Comment by onevcat** [comment]
It is a known issue of Xcode beta, that the 32bit slice of the Swift standard library is not contained in the SDK. The problem is still there in Xcode 12 beta 2. I guess Apple would fix it in a later version before Xcode 12 can be finally released. 

If the deploy target of your project is iOS 11 or later, you can choose to use the `fix/xcode12` branch temporarily to make it build with Carthage.

**Comment by onevcat** [comment]
@kkdayitbobson We now have a better solution without changing the deployment target here: #154 

Feel free to switch to `fix/xcode12-string-variant` to build the framework!

**Comment by danl3v** [comment]
The way I have diagnosed these issues is:
1) Open the project in Xcode 12
2) Archive the project to a generic device
3) The output error should give you a file name
4) Brute force: look through the file for substrings, modify/comment out code until you isolate the issue (Sadly Xcode gives no line numbers or any actual indication as to where the issue is)

**Comment by onevcat** [comment]
This issue was resolved in Xcode 12 beta 4. Now Xcode contains a proper piece of Swift library for 32-bit devices.
