### ISSUE TITLE
Cannot build on Xcode 12 beta for simulators

### ISSUE THREAD

**Issue by ldbchan** [line/line-sdk-ios-swift#160]
## Is it a security issue?

No

## What happened actually?

With `Build Active Architecture Only` set to NO, building for any simulator fails at the stage "Compile Swift source files (arm64)". While it works fine when building for physical devices.

```swift
import LineSDK

class LineAuthenticationSession {
    typealias LineAPI = LineSDK.API // error: No type named 'API' in module 'LineSDK'

    func isTokenError(_ error: LineSDKError) -> Bool { // error: Cannot find type 'LineSDKError' in scope
    }

    func login() {
        LoginManager.shared.login(permissions: [.profile]) { _ in  // error: Cannot find 'LoginManager' in scope
        }
    }
}
```

## Your environment?

- LINE SDK version: 5.5.1
- SDK installation method: add xcframework manually
- Xcode version: Xcode 12.0 beta 5 (12A8189h) and previous beta versions

## Sample project

N/A

**Comment by onevcat** [comment]
I don't think it is an issue of LINE SDK. But instead, it should be an issue of Xcode. There is very little we can do in LINE SDK for it. You can try to send Apple feedback since Xcode 12 is still in beta.

By specifying `ONLY_ACTIVE_ARCH` to NO with another `ARCHS_STANDARD` (x86_64 when you are selecting simulator), Xcode needs to merge the SDK module. However, it seems that this error happens during the process:

> Command MergeSwiftModule failed with a nonzero exit code

Maybe it is related to this https://github.com/Carthage/Carthage/issues/3019

@ldbchan  May I know do you want to set `Build Active Architecture Only` to NO even in your debug period? I personally suggest you keep it to `NO` for Debug configuration to speed up your build (and also avoid this error from Xcode).

**Comment by ldbchan** [comment]
Just figured this issue happens to other SDKs as well. I believe it is of Xcode as you said.

> May I know why do you want to set Build Active Architecture Only to NO even in your debug period?

We need `ONLY_ACTIVE_ARCH=NO` for internal testings, though it isn't necessary to be `NO` when building for simulators. I think the best solution for now is to have separate configuration for simulators. Thanks for your suggestion.

**Comment by onevcat** [comment]
Since there is nothing we can do to fix it, I am closing it. Let's wait and see whether this problem would still be there in the releasing versions of Xcode 12.
