### ISSUE TITLE
Error when using LineSDK in OC project

### ISSUE THREAD

**Issue by hw20101101** [line/line-sdk-ios-swift#162]
## Is it a security issue?

no

## What did you do?

After I integrate LineSDK with pods, I get an error when calling loginWithPermissions:permissions method

## What did you expect?

I hope I can use LineSDK normally in OC projects

## What happened actually?

error，EXC_BAD_ACCESS

## Your environment?

pod 'LineSDKSwift/ObjC', '~> 5.0'

Xcode 12.0 beta 5 

iOS 12.4.8

## Sample project

https://github.com/hw20101101/H200914_Test_Protocol

<img width="1372" alt="WX20200919-180001@2x" src="https://user-images.githubusercontent.com/9107226/93664558-743ca980-faa2-11ea-8a43-15a462654b82.png">

**Comment by onevcat** [comment]
Hi,

It seems that you are passing a `nil` to the `parameters` in the login method. https://github.com/hw20101101/H200914_Test_Protocol/blob/master/H200914_Test_Protocol/ViewController.m#L38

You should not do that since this `parameters` only accept a non-null value:

![截屏2020-09-23 11 06 47](https://user-images.githubusercontent.com/1019875/93956478-48b10c00-fd8d-11ea-9303-ff602ce6526d.png)

Try to remove the `parameters:nil` from your code, or set a `LineSDKLoginManagerParameters` value to it if you need any additional parameters. That should solve it.
