### ISSUE TITLE
Sometimes crashing when calling line-sdk-login in Unreal Engine

### ISSUE THREAD

**Issue by kjt0429** [line/line-sdk-ios-swift#172]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> I made a CPP-plugin with line-sdk-ios-swift and called line login in Unreal Engine build.

## What did you expect?

> line login success

## What happened actually?

> Sometimes crashing when calling line-sdk-login in Unreal Engine build.

## Your environment?

> Xcode 13.1, Unreal Engine 4.25.4, Line SDK 5.7.0, iOS 12~14 test device

## Sample project

> Result debugging

```swift
class AppUniversalLinkFlow {
    
    let url: URL
    let onNext = Delegate<Bool, Void>()
    
    init(parameter: LoginProcess.FlowParameters) {
        let universalURLBase = URL(string: Constant.lineWebAuthUniversalURL)!
        url = universalURLBase.appendedLoginQuery(parameter)
    }
    
    func start() {
        // crash point!!
        UIApplication.shared.open(url, options: [.universalLinksOnly: true]) {
            opened in
            self.onNext.call(opened)
        }
    }
}
```

**Comment by onevcat** [comment]
@kjt0429 Thanks for the report. Is there any more information like crash stack or screenshot? It would help us to track and know the crash better.

**Comment by kjt0429** [comment]
@onevcat Thanks for checking out my issue. I marked the crash point in the line code. There are no screenshots due to the crash situation. There are no significant logs.

**Comment by onevcat** [comment]
With the information provided now, it is too hard for us to track the issue. Since it crashes in the line

```
UIApplication.shared.open(url, options: [.universalLinksOnly: true])
```

is totally code from Apple and iOS. There is almost no way we can do anything about it.

The only suggestion from mine is, if it is possible to check the `url` value here, see whether it contains any special characters. If the url is fine, then maybe it is some restriction of either Unreal or Apple that stop a url being opened. In this case, there should usually some message in the console to explain it more.

Since there is no way to continue the investigation, please allow me to close it for now. Feel free to reopen it if there is any new information or anyone encounters the same problem. 🙏
