### ISSUE TITLE
How to use the One-Time Sharing Function

### ISSUE THREAD

**Issue by piosa** [line/line-sdk-ios-swift#181]
I want to test the function of share content with Line friend, and try the One-Time Sharing. 

Also I used the LineSDKSample project to test the share function and select the Login Permissions like this

![IMG_7012](https://user-images.githubusercontent.com/1757920/195795351-355c35cf-6d1b-4df6-aa93-4cef669119a7.PNG)

but I can not login with One-Time Sharing Permission

![IMG_7011](https://user-images.githubusercontent.com/1757920/195796775-d04818e6-3a7e-41c6-90e4-658c41aafc79.PNG)

with my channel had not the One-Time Sharing Permission, how can I add the One-Time Sharing Permission to my channel, there is not any edit option for the channel permission.

<img width="350" alt="snap" src="https://user-images.githubusercontent.com/1757920/195796396-22845192-3115-4251-8d02-8ae42bfb2357.png">

Thanks for your help!

**Comment by onevcat** [comment]
Hi,

The One-Time Sharing feature and its related APIs are now only provided to some internal partners. It requires a special permission for your channel and I would suggest you try to contact the [LINE for Business team](https://www.linebiz.com/jp/partner/) for more information about the current policy.

Since it is not a technical issue, please allow me to close it.
