### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by solitarysp** [line/line-sdk-ios-swift#194]
## What did you do?

- When I build my app I get the error `ld: symbol(s) not found for architecture arm64` on file `OpenChatCreatingController` and `ShareViewController ` with cause not found `_swift_stdlib_isStackAllocationSafe`

## What did you expect?

> Build with `arm64` successfully

## What happened actually?

>[ Please describe what happened actually.](ld: symbol(s) not found for architecture arm64)

## Your environment?

> Some information of the environment in which the issue happened. LINE SDK version, Xcode version, iOS version, etc.
-  LineSDKSwift (5.8.1):
- Xcode 14.2
Build version 14C18

**Comment by onevcat** [comment]
Your error 

```
Undefined symbols for architecture arm64:
  "_swift_stdlib_isStackAllocationSafe", referenced from:
```

It means something inside Swift is missing when building your app. Basically, it is caused by the Swift standard library not being in the search path so Xcode cannot find it.

It is much more possibly related to some malformed or wrong project settings in your project instead of something in the LINE SDK Swift. Can you first try and make sure that it can be built in a newly create Xcode project for arm64?

**Comment by solitarysp** [comment]
@onevcat What version of swift should I use?
