### ISSUE TITLE
How to disable the AppUniversalLinkFlow

### ISSUE THREAD

**Issue by verny-tran** [line/line-sdk-ios-swift#197]
Hello~ I want to disable the `AppUniversalLinkFlow` in LINE iOS SDK, only use `AppAuthSchemeFlow`.

-> How could I achieve that? Since for the case **if the device has already installed the LINE app but not logged in yet**.
-> The Universal link will open the Safari Webpage automatically. And I am unable to access those private functions in the SDK; please assist me in resolving this issue.

**Comment by onevcat** [comment]
Ummm, I guess there is now no option to skip the `AppUniversalLinkFlow`. However, if set correctly, the `AppAuthSchemeFlow` should also work if the `AppUniversalLinkFlow` fails. Can you confirm that you have added the `lineauth2` to the query scheme in your Info.plist? 

```xml
<key>LSApplicationQueriesSchemes</key>
<array>
    <!-- Specify URL scheme to use when launching LINE from your app. -->
    <string>lineauth2</string>
</array>
```

It is necessary for LINE SDK to determine whether LINE is installed on the device, due to the limitation of iOS's [`canOpenURL(_:)` method](https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl).



> If you link your app on or after iOS 9.0, you must declare the URL schemes you pass to this method by adding the LSApplicationQueriesSchemes key to your app's Info.plist file. This method always returns false for undeclared schemes, even if the device doesn’t have a registered app installed. Apps linked on or after iOS 15 are limited to a maximum of 50 entries in the LSApplicationQueriesSchemes key. To learn more about the key, see LSApplicationQueriesSchemes.

**Comment by verny-tran** [comment]
Yes of course I have added the `lineauth2` query scheme, and I also acknowledged that it'll fallback to `AppAuthSchemeFlow` if fails.

-> But my colleagues doesn't want to use the `AppUniversalLinkFlow` at all. 

Because their opinion is: 

> "If you have the LINE app installed but are not currently logged in. Then, rather than navigating to the Safari webpage, you should stop at the app to login."

-> As a result, I have this inquiry. But, since you've informed that there are no other possibilities, I believe I'll have to explain the issue to them. Thank you very much for your assistance.
