### ISSUE TITLE
Using `NSLock` in `SessionDelegate` might lead to deadlock

### ISSUE THREAD

**Issue by congnc1** [line/line-sdk-ios-swift#94]
A `NSRecursiveLock` is safer here. When two actions( add/remove) occur at the same time, we may fall into a deadlock.

**Comment by onevcat** [comment]
@congnc1 Thank you for the suggestion.

Using of `NSLock` is expected and designed as it is here.

In `SessionDelegate`, we do not have any recursive code for locking and unlocking, so I think a simple `NSLock` is enough.

`NSRecursiveLock` does "hide" the problem of possibility for manipulating the lock from the same queue. However, it should be categorized as a programmer error (an error of our repo maintainers) and we would want it to be exposed as soon as possible, instead of being hidden for long.

**Comment by onevcat** [comment]
If you have any case that this causes a deadlock, please let me know and I am glad to look at it deeper!

**Comment by onevcat** [comment]
Adding and removing a task (or say, acquiring a lock multiple times before unlocking in the same thread) will never happen at the same time since the delegate is running on a private serial queue.

However, there is indeed a case that two `add` methods acquire the same lock. It may happen when initializing two API calls from the same concurrency thread. Although it is a very rare case and almost be due to a misuse of the SDK, I will give it a fix.

Thanks!

**Comment by congnc1** [comment]
You're welcome.

**Comment by onevcat** [comment]
Umm,

I think I was wrong on my last comment. Since there is no recursive operation in the `SessionDelegate` related methods, and there should be no chance that for outside users to create such a recursive operation, the `NSRecursiveLock` should be not necessary there.

I added a test in https://github.com/line/line-sdk-ios-swift/pull/95 to verify that there is no deadlock around on it.

I am closing it for now. Please let me know if I am wrong with it!

Thank you.

**Comment by congncif** [comment]
You’re right. Maybe I was overthinking. Because the key returned is immediately so no two tasks will be able to acquire the lock on the same thread.
Good job.

**Comment by onevcat** [comment]
Never mind! Thank you anyway for suggesting this. It makes me rethink it. It is a great complementary to our test cases!
